// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/auth/data/models/user_box_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 237031838721780581),
      name: 'UserBoxEntity',
      lastPropertyId: const obx_int.IdUid(11, 2793058360460505094),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5136623347395591838),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3278307212953951806),
            name: 'uid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 8893327681051370746)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1101738829443064116),
            name: 'persId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1672552917529084539),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6806276439578808872),
            name: 'nameAr',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4056144643559464663),
            name: 'nameEn',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5529998534673772578),
            name: 'phone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5863488654760582137),
            name: 'address',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2115970929426658604),
            name: 'plan',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 3288175302219881210),
            name: 'memberSince',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 2793058360460505094),
            name: 'birthday',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 237031838721780581),
      lastIndexId: const obx_int.IdUid(1, 8893327681051370746),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    UserBoxEntity: obx_int.EntityDefinition<UserBoxEntity>(
        model: _entities[0],
        toOneRelations: (UserBoxEntity object) => [],
        toManyRelations: (UserBoxEntity object) => {},
        getId: (UserBoxEntity object) => object.id,
        setId: (UserBoxEntity object, int id) {
          object.id = id;
        },
        objectToFB: (UserBoxEntity object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final emailOffset =
              object.email == null ? null : fbb.writeString(object.email!);
          final nameArOffset =
              object.nameAr == null ? null : fbb.writeString(object.nameAr!);
          final nameEnOffset =
              object.nameEn == null ? null : fbb.writeString(object.nameEn!);
          final phoneOffset =
              object.phone == null ? null : fbb.writeString(object.phone!);
          final addressOffset =
              object.address == null ? null : fbb.writeString(object.address!);
          final planOffset =
              object.plan == null ? null : fbb.writeString(object.plan!);
          final memberSinceOffset = object.memberSince == null
              ? null
              : fbb.writeString(object.memberSince!);
          final birthdayOffset = object.birthday == null
              ? null
              : fbb.writeString(object.birthday!);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addInt64(2, object.persId);
          fbb.addOffset(3, emailOffset);
          fbb.addOffset(4, nameArOffset);
          fbb.addOffset(5, nameEnOffset);
          fbb.addOffset(6, phoneOffset);
          fbb.addOffset(7, addressOffset);
          fbb.addOffset(8, planOffset);
          fbb.addOffset(9, memberSinceOffset);
          fbb.addOffset(10, birthdayOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final persIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final nameArParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final nameEnParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final phoneParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final addressParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final planParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final memberSinceParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 22);
          final birthdayParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 24);
          final object = UserBoxEntity(
              uid: uidParam,
              persId: persIdParam,
              email: emailParam,
              nameAr: nameArParam,
              nameEn: nameEnParam,
              phone: phoneParam,
              address: addressParam,
              plan: planParam,
              memberSince: memberSinceParam,
              birthday: birthdayParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [UserBoxEntity] entity fields to define ObjectBox queries.
class UserBoxEntity_ {
  /// see [UserBoxEntity.id]
  static final id =
      obx.QueryIntegerProperty<UserBoxEntity>(_entities[0].properties[0]);

  /// see [UserBoxEntity.uid]
  static final uid =
      obx.QueryStringProperty<UserBoxEntity>(_entities[0].properties[1]);

  /// see [UserBoxEntity.persId]
  static final persId =
      obx.QueryIntegerProperty<UserBoxEntity>(_entities[0].properties[2]);

  /// see [UserBoxEntity.email]
  static final email =
      obx.QueryStringProperty<UserBoxEntity>(_entities[0].properties[3]);

  /// see [UserBoxEntity.nameAr]
  static final nameAr =
      obx.QueryStringProperty<UserBoxEntity>(_entities[0].properties[4]);

  /// see [UserBoxEntity.nameEn]
  static final nameEn =
      obx.QueryStringProperty<UserBoxEntity>(_entities[0].properties[5]);

  /// see [UserBoxEntity.phone]
  static final phone =
      obx.QueryStringProperty<UserBoxEntity>(_entities[0].properties[6]);

  /// see [UserBoxEntity.address]
  static final address =
      obx.QueryStringProperty<UserBoxEntity>(_entities[0].properties[7]);

  /// see [UserBoxEntity.plan]
  static final plan =
      obx.QueryStringProperty<UserBoxEntity>(_entities[0].properties[8]);

  /// see [UserBoxEntity.memberSince]
  static final memberSince =
      obx.QueryStringProperty<UserBoxEntity>(_entities[0].properties[9]);

  /// see [UserBoxEntity.birthday]
  static final birthday =
      obx.QueryStringProperty<UserBoxEntity>(_entities[0].properties[10]);
}
